### ISSUE TITLE
Feature: OR to RR conversion in TSA

### ISSUE THREAD

**Issue by lilleoel** [AnneLyng/RTSA#8]
Hi,

My name is Tom Payne - I'm a researcher from Sydney, Australia, focussing mostly on meta-analysis. I'm a huge fan of the TSA software - thanks for the great ongoing work that you're doing!

I'm just emailing because of a query I have with the software. I note that when 'odds ratio' is selected as the measure of effect for the meta-analysis, when one then selects the 'based on trials at low risk of bias' option for the relative risk reduction (for calculation of the required information size) - the figure provided is actually a reflection of the odds ratio rather than the risk ratio. There is no conversion from the point estimate of the odds ratio into a risk ratio. For example, if the point estimate for the odds ratio meta-analysis was 0.7, when TSA software calculates the relative risk reduction, it gives the figure 30%; but this is the reduction in odds, not the reduction in risk. An odds ratio of 0.7, arbitrarily assuming a baseline prevalence of 40%, corresponds to a risk ratio of 0.8, and hence a RRR of 20%.

I was wondering if this was a mistake in the software or if I was missing something? Just thought I would reach out and check because as I said I'm a fan of the software and wouldn't want researchers to accidentally be getting the wrong relative risk reductions for their calculations.

Cheers,

Tom

**Comment by joachimmilan** [comment]
Hi Tom,

I'm glad you enjoy using the TSA software. Please do note that this GitHub page is dedicated to the R implementation of the TSA software: the RTSA package. 

Nonetheless, you raise an important question that I will take forward to the team.

Bw, Joachim

**Comment by lilleoel** [comment]
Closed
